### ISSUE TITLE
stats do not work

### ISSUE THREAD

**Issue by vad1m4** [vad1m4/tgeb#4]
Exception in thread Thread-2 (schedule_loop):     Traceback (most recent call last):                  File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner    self.run()                                      File "/data/data/com.termux/files/usr/lib/python3.11/threading.py", line 982, in run                  self._target(*self._args, **self._kwargs)       File "/data/data/com.termux/files/home/tg_electricity_bot_oop/electricity_bot/funcs.py", line 184, in schedule_loop                                     schedule.run_pending()                          File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/schedule/__init__.py", line 854, in run_pending                                      default_scheduler.run_pending()                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/schedule/__init__.py", line 101, in run_pending                                      self._run_job(job)                              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/schedule/__init__.py", line 173, in _run_job
    ret = job.run()                                         ^^^^^^^^^                                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/schedule/__init__.py", line 691, in run                                              ret = self.job_func()                                   ^^^^^^^^^^^^^^^                           File "/data/data/com.termux/files/home/tg_electricity_bot_oop/electricity_bot/funcs.py", line 143, in stats_job                                         stats(bot, get_date(-1))                        File "/data/data/com.termux/files/home/tg_electricity_bot_oop/electricity_bot/funcs.py", line 194, in stats                                             total += bot.outages_storage.lasted(outage, date)                                               TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by vad1m4** [comment]
line 188 in funcs.py

need to replace the default value as I did in storage.py. prolly will fix it
